name: Bug Report
description: Reportar un bug o comportamiento inesperado
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - alejandrolmeida

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este bug. Por favor completa la siguiente información para ayudarnos a resolver el problema.

  - type: textarea
    id: description
    attributes:
      label: Descripción del Bug
      description: Una descripción clara y concisa de cuál es el bug.
      placeholder: Describe el bug aquí...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ejecutar comando '...'
        2. Abrir notebook '...'
        3. Ejecutar celda '...'
        4. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Una descripción clara de lo que esperabas que ocurriera.
      placeholder: Debería...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Una descripción clara de lo que ocurrió realmente.
      placeholder: En su lugar, ocurrió...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs de Error
      description: Si aplica, pega los logs de error relevantes.
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "...", line X, in <module>
            ...
        Error: ...

  - type: dropdown
    id: component
    attributes:
      label: Componente Afectado
      description: ¿Qué parte del proyecto está afectada?
      options:
        - Notebooks
        - Scripts de Training
        - Scripts de Deployment
        - Workflows de CI/CD
        - Infraestructura (Bicep)
        - Documentación
        - Copilot Chat Modes
        - Otro
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Versión de Python
      description: Ejecuta `python --version`
      placeholder: "3.11.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Sistema Operativo
      description: ¿Qué OS estás usando?
      placeholder: "Ubuntu 22.04 / Windows 11 / macOS 14"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Versiones de Dependencias
      description: Ejecuta `pip list` y pega las versiones relevantes
      render: text
      placeholder: |
        pandas==2.1.3
        scikit-learn==1.3.2
        azure-ai-ml==1.12.0

  - type: dropdown
    id: environment
    attributes:
      label: Entorno
      description: ¿Dónde ocurre el error?
      options:
        - Local (laptop/workstation)
        - Azure ML Compute Instance
        - Azure ML Compute Cluster
        - GitHub Actions (CI/CD)
        - Azure Container Instance
        - Otro
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si aplica, añade screenshots para ayudar a explicar el problema.
      placeholder: Arrastra y suelta imágenes aquí

  - type: textarea
    id: additional
    attributes:
      label: Información Adicional
      description: Añade cualquier otro contexto sobre el problema aquí.
      placeholder: |
        - ¿Funcionó anteriormente?
        - ¿Cambios recientes en el código?
        - ¿Workarounds que has intentado?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Por favor confirma lo siguiente
      options:
        - label: He buscado en issues existentes y no encontré uno similar
          required: true
        - label: He incluido toda la información necesaria para reproducir el bug
          required: true
        - label: He probado con la última versión del proyecto
          required: false
