name: training-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - numpy=1.24.3
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - pip:
      # ML & Data
      - xgboost==2.0.2
      - lightgbm==4.1.0
      - optuna==3.4.0

      # MLflow & Tracking
      - mlflow==2.9.1
      - azure-ai-ml==1.12.0

      # Data Quality
      - great-expectations==0.18.8
      - pandera==0.17.2
      - evidently==0.4.8

      # Azure SDK
      - azure-identity==1.15.0
      - azure-storage-blob==12.19.0
      - azure-storage-filedatalake==12.14.0

      # Utilities
      - joblib==1.3.2
      - pyyaml==6.0.1
      - python-dotenv==1.0.0

      # Development
      - pytest==7.4.3
      - pytest-cov==4.1.0
      - ruff==0.1.6
      - black==23.11.0
